// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dndb

import (
	"database/sql"
)

type Projects struct {
	ProjectID   int64          `json:"project_id"`
	ProjectName sql.NullString `json:"project_name"`
}

type Tasks struct {
	TaskID        int64          `json:"task_id"`
	ParentID      sql.NullInt64  `json:"parent_id"`
	ProjectID     sql.NullInt64  `json:"project_id"`
	Name          interface{}    `json:"name"`
	Description   sql.NullString `json:"description"`
	Priority      sql.NullString `json:"priority"`
	Difficulty    int64          `json:"difficulty"`
	Duration      int64          `json:"duration"`
	TimeFixed     int64          `json:"time_fixed"`
	TimeFixedTime sql.NullString `json:"time_fixed_time"`
	CreatedAt     sql.NullString `json:"created_at"`
	UpdatedAt     sql.NullString `json:"updated_at"`
}
